baseURL: http://example.org/
languageCode: en-us
title: Abhiram | xbr
theme : 'smigle'

menu:
  main: # Change menu as needed
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 3
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 4
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 5
  
params:
  dateFmt: "02-01-2006"
  brandIconFile: "ddd.png"



social:
    - name: GitHub
      url: https://github.com/ian-s-mcb


      
name: smigle
license: MIT
licenselink: https://gitlab.com/ian-s-mcb/smigle-hugo-theme/-/blob/master/LICENSE
description: Minimal Hugo theme using a Monospace font and free from tracking or external dependencies
homepage: https://gitlab.com/ian-s-mcb/smigle-hugo-theme
tags:
  - blog
  - portfolio
  - minimal
  - monospace
  - simple
  - clean
  - light
  - responsive
  - fast
  - no-js
  - no-tracking
  - privacy
features: []
min_version: 0.41.0
author:
  name: Ian S. McBride
  homepage: https://iansmcb.gq/
  

# If porting an existing theme
original:
  name: smol
  homepage: https://sumnerevans.com/
  repo: https://github.com/sumnerevans/smol
module:
  hugoVersion:
    extended: false
    max: ""
    min: 0.41.0
